import { ROLE_CODES, type RoleCode } from "@/config/roles.config";

export const PERMISSION_CODES = {
  VIEW_OWN_TASKS: "VIEW_OWN_TASKS",
  VIEW_ASSIGNED_TRAINEES: "VIEW_ASSIGNED_TRAINEES",
  VIEW_ALL_TRAINEES: "VIEW_ALL_TRAINEES",
  CHECK_IN_LEARN: "CHECK_IN_LEARN",
  CONFIRM_ASSIGNED_PRACTICE: "CONFIRM_ASSIGNED_PRACTICE",
  WRITE_ASSIGNED_NOTES: "WRITE_ASSIGNED_NOTES",
  EDIT_EXISTING_TASKS: "EDIT_EXISTING_TASKS",
  MANAGE_TASKS: "MANAGE_TASKS",
  MANAGE_PEOPLE: "MANAGE_PEOPLE",
  VIEW_AUDIT_LOG: "VIEW_AUDIT_LOG",
} as const;

export type PermissionCode = (typeof PERMISSION_CODES)[keyof typeof PERMISSION_CODES];

export const ROLE_PERMISSIONS = {
  [ROLE_CODES.TRAINEE]: [PERMISSION_CODES.VIEW_OWN_TASKS, PERMISSION_CODES.CHECK_IN_LEARN],
  [ROLE_CODES.MENTOR]: [
    PERMISSION_CODES.VIEW_ASSIGNED_TRAINEES,
    PERMISSION_CODES.CONFIRM_ASSIGNED_PRACTICE,
    PERMISSION_CODES.WRITE_ASSIGNED_NOTES,
  ],
  [ROLE_CODES.SUPERVISOR]: [
    PERMISSION_CODES.VIEW_ALL_TRAINEES,
    PERMISSION_CODES.CONFIRM_ASSIGNED_PRACTICE,
    PERMISSION_CODES.WRITE_ASSIGNED_NOTES,
    PERMISSION_CODES.EDIT_EXISTING_TASKS,
  ],
  [ROLE_CODES.ADMIN]: Object.values(PERMISSION_CODES),
} as const satisfies Record<RoleCode, readonly PermissionCode[]>;

export type RolePermissions = typeof ROLE_PERMISSIONS;
