export const UI_TEXT = {
  employeeId: "工号",
  name: "姓名",
  password: "密码",
  login: "登录",
  register: "注册",
  loggingIn: "登录中…",
  registering: "注册中…",
  loginPending: "正在验证登录信息",
  registerPending: "正在创建新人账号",
  loginError: "工号或密码不正确，请重试",
  registerError: "注册失败，请稍后重试",
  registerSuccess: "注册成功，请使用刚才设置的密码登录",
  registerPasswordHint: "至少 8 位，请设置仅自己知道的密码",
  loginWelcome: "欢迎回来",
  loginHint: "请使用公司分配的工号和密码登录",
  accountAccess: "账号登录与注册",
  accountAccessTitle: "开始使用成长追踪",
  accountAccessHint: "登录已有账号，或使用工号创建新人账号",
  navigation: "主导航",
  openNavigation: "打开导航菜单",
  roleView: "角色视角",
  home: "首页",
  homeHint: "请选择左侧导航开始工作",
  backHome: "返回首页",
  learn: "学",
  drill: "练",
  action: "干",
  learnRate: "学习完成率",
  dueRate: "截至今日完成率",
  focusDirection: "重点方向",
  mentorConfirmation: "导师确认",
  pendingConfirmation: "待确认",
  overdue: "逾期",
  today: "今日",
  completed: "已完成",
  incomplete: "未完成",
  upcoming: "未到期",
  noTasks: "暂无任务",
  progressTitle: "90 天成长进度",
  dueCompletion: "截至今日完成率",
  drillCompletion: "Drill 完成率",
  actionCompletion: "Action 完成率",
  trainingDay: "培养 Day",
  learningProgress: "学习总进度",
  stageFilter: "阶段",
  dimensionFilter: "维度",
  statusFilter: "状态",
  taskSearch: "搜索任务",
  allStages: "全部阶段",
  allDimensions: "全部维度",
  allStatuses: "全部状态",
  applyFilters: "应用筛选",
  resetFilters: "重置筛选",
  noFilterResults: "没有符合当前筛选条件的任务",
  viewDetails: "查看详情",
  saveFailed: "保存失败，请稍后重试",
} as const;

export type UiText = typeof UI_TEXT;
export type UiTextKey = keyof UiText;
export type UiTextValue = UiText[UiTextKey];
